#
# gosund sp111 smart plug with power sensor
#
esphome:
  name: gosund-sp111
  platform: ESP8266
  board: esp8285
  project: 
    name: "wonsky007.gosund-sp111"
    version: "1.0.0"

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#failback ap
  ap:
    ssid: "gosund-sp111"
    password: "12345678"

captive_portal: 

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:

# TIME
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
web_server:
  port: 80

sensor:
  - platform: total_daily_energy
    name: "Daily Power Usage"
    power_id: "sp111_power"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:calendar-clock
    accuracy_decimals: 3
    
  # Power sensor
  - platform: hlw8012
    voltage_divider: 765 # Calibration value
    current_resistor: 0.001
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 3
    update_interval: 5s
    # Current sensor
    current:
      id: sp111_current
      name: Current
      unit_of_measurement: A
      accuracy_decimals: 3
    # Voltage sensor
    voltage:
      id: sp111_voltage
      name: Voltage
      unit_of_measurement: V
      accuracy_decimals: 1
    # Power sensor
    power:
      id: sp111_power
      name: Power consumption
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
      - multiply: 0.5



binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    name: Button
    pin:
      number: GPIO13
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  # Switch to toggle the relay
  - platform: gpio
    id: relay
    name: Relay
    pin: GPIO15
    restore_mode: ALWAYS_ON
